/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  config_bin: () => import("@/views/config/bin/index.vue"),
  config_broadcast: () => import("@/views/config/broadcast/index.vue"),
  config_routing: () => import("@/views/config/routing/index.vue"),
  config_telegram: () => import("@/views/config/telegram/index.vue"),
  home: () => import("@/views/home/index.vue"),
  management_user: () => import("@/views/management/user/index.vue"),
  payment_console: () => import("@/views/payment/console/index.vue"),
  payment_overview: () => import("@/views/payment/overview/index.vue"),
};
